<#
.SYNOPSIS
    Generates web/config.js from app/google-services.json.

.DESCRIPTION
    The share player reads its Firestore project id and web API key from web/config.js. Both are
    public values - security comes from the Firestore rules, which only expose unexpired share
    documents - but they differ per project, so they are generated rather than committed.

    Run this once after downloading google-services.json, then deploy hosting.
#>
[CmdletBinding()]
param(
    [string] $ServicesJson = (Join-Path $PSScriptRoot '..\app\google-services.json'),
    [string] $Output       = (Join-Path $PSScriptRoot '..\web\config.js')
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

if (-not (Test-Path -LiteralPath $ServicesJson)) {
    throw "google-services.json not found at $ServicesJson. Complete step 4 of docs/SETUP.md first."
}

$config = Get-Content -LiteralPath $ServicesJson -Raw -Encoding UTF8 | ConvertFrom-Json

$projectId = $config.project_info.project_id
if (-not $projectId) { throw "google-services.json has no project_info.project_id" }

# The Android client carries the same browser-usable API key the web player needs.
$apiKey = $config.client[0].api_key[0].current_key
if (-not $apiKey) { throw "google-services.json has no client[0].api_key[0].current_key" }

$body = @"
// Generated by tools/gen-web-config.ps1 - do not edit by hand.
// These values are public by design; the Firestore rules are what protect the data.
window.THUNDERPLAY_CONFIG = {
  projectId: "$projectId",
  apiKey: "$apiKey"
};
"@

Set-Content -LiteralPath $Output -Value $body -Encoding UTF8
Write-Host "Wrote $Output for project $projectId" -ForegroundColor Green
Write-Host "Next: npx firebase-tools deploy --only hosting" -ForegroundColor DarkGray
