// Generated by tools/gen-web-config.ps1 - do not edit by hand.
// These values are public by design; the Firestore rules are what protect the data.
window.THUNDERPLAY_CONFIG = {
  projectId: "thunder-play-2ad15",
  apiKey: "AIzaSyBRwBBA7Cpgj8-t3PVaydDxNTlrrYEp5zI"
};
